trigger:
- azure-pipelines

pool:
  vmImage: macOS-13

steps:
- script: Vendor\Binaries\Premake\Windows\premake5.exe --file=Build.lua xcode4
  displayName: 'Run premake'

- task: Xcode@5
  inputs:
    actions: 'build'
    xcWorkspacePath: 'New Project.xcworkspace'
    xcodeVersion: '14.2'