trigger:
- azure-pipelines

pool:
  vmImage: macOS-13

steps:
- script: Vendor/Binaries/Premake/macOS/premake5 --file=Build.lua xcode4
  displayName: 'Run premake'

- task: Xcode@5
  inputs:
    actions: 'build'
    xcWorkspacePath: 'New Project.xcworkspace'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_14.2.app'