trigger:
- azure-pipelines

pool:
  vmImage: macOS-13

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: jretterer-prol
    userRepository: mozilla/sccache 
    defaultVersionType: 'latest'
    itemPattern: 'sccache-v0.8.0-x86_64-apple-darwin.tar.gz '
    downloadPath: '$(System.ArtifactsDirectory)' 

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/sccache-v0.8.0-x86_64-apple-darwin.tar.gz'
    destinationFolder: $(System.ArtifactsDirectory)/sccache

- script: |
    cat > $(System.ArtifactsDirectory)/sccache/sccache_clang << EOF
    #!/bin/sh
    exec $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-apple-darwin/sccache /usr/bin/clang "$@"
    EOF
    chmod 755 $(System.ArtifactsDirectory)/sccache/sccache_clang
    cat $(System.ArtifactsDirectory)/sccache/sccache_clang
  displayName: 'Create sccache_clang'

- script: |
    cat > $(System.ArtifactsDirectory)/sccache/sccache_clang++ << EOF
    #!/bin/sh
    exec $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-apple-darwin/sccache /usr/bin/clang++ "$@"
    EOF
    chmod 755 $(System.ArtifactsDirectory)/sccache/sccache_clang++
    cat $(System.ArtifactsDirectory)/sccache/sccache_clang++
  displayName: 'Create sccache_clang++'

- script: $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-apple-darwin/sccache --start-server
  displayName: 'Start sccache'

- script: Vendor/Binaries/Premake/macOS/premake5 --file=Build.lua xcode4
  displayName: 'Run premake'

- task: Xcode@5
  inputs:
    actions: 'build'
    xcWorkspacePath: 'New Project.xcworkspace'
    scheme: 'App'
    configuration: 'Debug'
    sdk: 'macosx13.1'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_14.2.app'
  env:
    CC: $(System.ArtifactsDirectory)/sccache/sccache_clang
    CXX: $(System.ArtifactsDirectory)/sccache/sccache_clang++

- script: $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-apple-darwin/sccache --stop-server
  displayName: 'Stop sccache'
  continueOnError: true