# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- script: Vendor/Binaries/Premake/Linux/premake5 --file=Build.lua gmake
  displayName: 'Run premake'

- script: make all
  displayName: 'Run make'
