trigger:
- azure-pipelines

pool:
  name: vmssagentspool

steps:
- script: apt install -y gcc-10 g++-10
  displayName: 'install gcc'

- task: DownloadGitHubRelease@0
  inputs:
    connection: jretterer-prol
    userRepository: mozilla/sccache 
    defaultVersionType: 'latest'
    itemPattern: 'sccache-v0.8.0-x86_64-unknown-linux-musl.tar.gz'
    downloadPath: '$(System.ArtifactsDirectory)' 

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/sccache-v0.8.0-x86_64-unknown-linux-musl.tar.gz'
    destinationFolder: $(System.ArtifactsDirectory)/sccache

- script: $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-unknown-linux-musl/sccache --start-server
  displayName: 'Start sccache'

- script: Vendor/Binaries/Premake/Linux/premake5 --file=Build.lua gmake
  displayName: 'Run premake'

- script: make all
  displayName: 'Run make'
  env:
    CC: $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-unknown-linux-musl/sccache /usr/bin/gcc-10
    CXX: $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-unknown-linux-musl/sccache /usr/bin/g++-10

- script: $(System.ArtifactsDirectory)/sccache/sccache-v0.8.0-x86_64-unknown-linux-musl/sccache --stop-server
  displayName: 'Stop sccache'