trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- script: Vendor/Binaries/Premake/Linux/premake5 --file=Build.lua gmake
  displayName: 'Run premake'

- script: make all
  displayName: 'Run make'
  env:
    CC: /usr/bin/gcc-10
    CXX: /usr/bin/g++-10