name: 'Windows Pipeline'

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- script: Vendor\Binaries\Premake\Windows\premake5.exe --file=Build.lua vs2022
  displayName: 'Run premake'

- scipt: dir
  displayName: 'list files'