name: 'Windows Pipeline'

trigger:
- azure-pipelines

pool:
  vmImage: windows-latest

steps:
- script: Vendor\Binaries\Premake\Windows\premake5.exe --file=Build.lua vs2022
  displayName: 'Run premake'

- task: VSBuild@1
  desplayName: 'msbuild'
  inputs:
    solution: 'New Project.sln'